astro_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as user_views
from django.views.generic.base import TemplateView
from newsletter import views
from accounts import views as user_views



urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include ('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),    
    path('', include('pages.urls')),
    path('store/', include('store.urls')),
    path('profile/', user_views.profile, name='profile'),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('voucher/', include('voucher.urls', namespace='voucher')),
    path('contact', include('contact_us.urls')),
    path('new/', views.new, name='new'),
    path('confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
    path('gallery/', include('gallery.urls')),
    path('management/', include('management.urls')),
    path('search/', include('search_app.urls')),
    path('terms/', views.terms, name='terms'),
    #path('newsletter/', include('newsletter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

management/urls.py
from django.urls import path
from .views import UserManagementView, UserListView, UserDetailView, UserDeleteView, UserUpdateView #, UserCreateView
from .views import ShopManagementView, CategoryListView, CategoryCreateView, CategoryDeleteView, CategoryUpdateView, CategoryDetailView
from .views import ProductListView, ProductCreateView, ProductDeleteView, ProductDetailView, ProductUpdateView
from .views import VoucherListView, VoucherCreateView, VoucherDeleteView, VoucherDetailView, VoucherUpdateView
from .views import ProfileListView, ProfileCreateView, ProfileDeleteView, ProfileDetailView, ProfileUpdateView
from .views import SubscriberListView, SubscriberCreateView, SubscriberDeleteView, SubscriberDetailView, SubscriberUpdateView
from .views import NewsletterListView, NewsletterCreateView, NewsletterDeleteView, NewsletterDetailView, NewsletterUpdateView
from .views import PictureListView, PictureCreateView, PictureDeleteView, PictureDetailView, PictureUpdateView
from .views import PictureOfTheMonthListView, PictureOfTheMonthDeleteView
from .views import SliderListView, SliderCreateView, SliderDeleteView
from accounts.views import signupView



app_name='management'


urlpatterns = [
    path('', UserManagementView.as_view(), name = 'management'),
    path('user_management/', UserListView.as_view(), name = 'users'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name = 'user_details'),
    path('user_add/', signupView, name = 'user_add'),
    path('user_delete/<int:pk>/', UserDeleteView.as_view(), name = 'user_delete'),
    path('user_update/<int:pk>/', UserUpdateView.as_view(), name = 'user_update'),

    path('profiles/', ProfileListView.as_view(), name = 'profiles'),
    path('profile_detail/<int:pk>/', ProfileDetailView.as_view(), name = 'profile_details'),
    path('profile_add/', ProfileCreateView.as_view(), name = 'profile_add'),
    path('profile_delete/<int:pk>/', ProfileDeleteView.as_view(), name = 'profile_delete'),
    path('profile_update/<int:pk>/', ProfileUpdateView.as_view(), name = 'profile_update'),

    path('subscribers/', SubscriberListView.as_view(), name = 'subscribers'),
    path('subscriber_detail/<int:pk>/', SubscriberDetailView.as_view(), name = 'subscriber_details'),
    path('subscriber_add/', SubscriberCreateView.as_view(), name = 'subscriber_add'),
    path('subscriber_delete/<int:pk>/', SubscriberDeleteView.as_view(), name = 'subscriber_delete'),
    path('subscriber_update/<int:pk>/', SubscriberUpdateView.as_view(), name = 'subscriber_update'),

    path('newsletters/', NewsletterListView.as_view(), name = 'newsletters'),
    path('newsletter_detail/<int:pk>/', NewsletterDetailView.as_view(), name = 'newsletter_details'),
    path('newsletter_add/', NewsletterCreateView.as_view(), name = 'newsletter_add'),
    path('newsletter_delete/<int:pk>/', NewsletterDeleteView.as_view(), name = 'newsletter_delete'),
    path('newsletter_update/<int:pk>/', NewsletterUpdateView.as_view(), name = 'newsletter_update'),

    path('shop_management/', ShopManagementView.as_view(), name = 'manage_shop'),
    path('shop_management/categories/', CategoryListView.as_view(), name = 'cats'),
    path('shop_management/categories/<slug:slug>/', CategoryDetailView.as_view(), name = 'cat_details'),
    path('shop_management/categories/category_add', CategoryCreateView.as_view(), name = 'cat_add'),
    path('shop_management/categories/category_delete/<slug:slug>/', CategoryDeleteView.as_view(), name = 'cat_delete'),
    path('shop_management/categories/category_update/<slug:slug>/', CategoryUpdateView.as_view(), name = 'cat_update'),

    path('shop_management/products/', ProductListView.as_view(), name = 'products'),
    path('shop_management/products/<slug:slug>/', ProductDetailView.as_view(), name = 'prod_details'),
    path('shop_management/products/product_add', ProductCreateView.as_view(), name = 'prod_add'),
    path('shop_management/products/product_delete/<slug:slug>/', ProductDeleteView.as_view(), name = 'prod_delete'),
    path('shop_management/products/product_update/<slug:slug>/', ProductUpdateView.as_view(), name = 'prod_update'),

    path('shop_management/sliders/', SliderListView.as_view(), name = 'sliders'),
    path('shop_management/products/slider_add', SliderCreateView.as_view(), name = 'slider_add'),
    path('shop_management/products/slider_delete/<int:pk>/', SliderDeleteView.as_view(), name = 'slider_delete'),

    path('shop_management/vouchers/', VoucherListView.as_view(), name = 'vouchers'),
    path('shop_management/vouchers/<int:pk>/', VoucherDetailView.as_view(), name = 'voucher_details'),
    path('shop_management/vouchers/product_add', VoucherCreateView.as_view(), name = 'voucher_add'),
    path('shop_management/vouchers/product_delete/<int:pk>/', VoucherDeleteView.as_view(), name = 'voucher_delete'),
    path('shop_management/vouchers/product_update/<int:pk>/', VoucherUpdateView.as_view(), name = 'voucher_update'),

    path('shop_management/pictures/', PictureListView.as_view(), name = 'pictures'),
    path('shop_management/pictures/<uuid:pk>/', PictureDetailView.as_view(), name = 'picture_details'),
    path('shop_management/pictures/picture_add', PictureCreateView.as_view(), name = 'picture_add'),
    path('shop_management/pictures/picture_delete/<uuid:pk>/', PictureDeleteView.as_view(), name = 'picture_delete'),
    path('shop_management/pictures/picture_update/<uuid:pk>/', PictureUpdateView.as_view(), name = 'picture_update'),

    path('shop_management/pictures_of_the_month/', PictureOfTheMonthListView.as_view(), name = 'pictures_of_the_month'),
    path('shop_management/pictures_of_the_month/picture_of_the_month_delete/<int:pk>/', PictureOfTheMonthDeleteView.as_view(), name = 'picture_of_the_month_delete'),

]

voucher/urls.py
from django.urls import path
from . import views

app_name = 'voucher'

urlpatterns = [
    path('apply/', views.voucher_apply, name='apply'),
]

management/models.py
from django.db import models

# Create your models here.

newsletter/models.py
from django.db import models
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Email, Content, Mail
from django.conf import settings

class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    conf_num = models.CharField(max_length=15)
    confirmed = models.BooleanField(default=False)

    # confirm (or not) the subscription (also casts to lower to stop duplication in DB due to different letter cases duplicating)
    def __str__(self):
        return self.email.lower() + " (" + ("not " if not self.confirmed else "") + "confirmed)"

# model for the newsletter (using sendgrid)
class Newsletter(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    subject = models.CharField(max_length=150)
    contents = models.FileField(upload_to='uploaded_newsletters/')

    def __str__(self):
        return self.subject + " " + self.created_at.strftime("%B %d, %Y")

    def send(self, request):
        contents = self.contents.read().decode('utf-8')
        subscribers = Subscriber.objects.filter(confirmed=True)
        sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
        for sub in subscribers:
            message = Mail(
                    from_email=settings.FROM_EMAIL,
                    to_emails=sub.email,
                    subject=self.subject,
                    html_content=contents + (
                        '<br><a href="{}/delete/?email={}&conf_num={}">Unsubscribe</a>.').format(
                            request.build_absolute_uri('/delete/'),
                            sub.email,
                            sub.conf_num))
            sg.send(message)

store/models.py
import uuid
from django.db import models
from django.urls import reverse

# shop models 

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    slug = models.SlugField(max_length=255)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)
    image_secondary = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('category_detail', args=[str(self.slug)])

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    slug = models.SlugField(max_length=255)
    name = models.CharField(max_length=250, unique=True)
    make = models.CharField(max_length=250, null=True)
    model = models.CharField(max_length=250, null=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, related_name ='products', on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return '/%s/%s/' % (self.category.slug, self.slug)

    def __str__(self):
        return self.name



class Slider(models.Model):
    slide = models.ForeignKey(Product, related_name ='slide', on_delete=models.SET_NULL, null=True)

voucher/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Voucher(models.Model):
    code = models.CharField(max_length=50, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    active = models.BooleanField()

def __str__(self):
    return self.code

management/forms.py
from django import forms 
from accounts.models import CustomUser
  
class UserForm(forms.ModelForm): 
  
    class Meta: 
        model = CustomUser
        fields = ['username', 'password', 'first_name', 'last_name', 'email', 'is_staff','can_upload_images','groups']

newsletter/forms.py
from django import forms

class SubscriberForm(forms.Form):
    email = forms.EmailField(label='Please enter your email below to learn about our latest offers, products and news',
                             max_length=100,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

voucher/forms.py
from django import forms
class VoucherApplyForm(forms.Form):
    code = forms.CharField()

newsletter/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from .models import Subscriber
from .forms import SubscriberForm
import random
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# random num for confirmation number
def random_digits():
    return "%0.12d" % random.randint(0, 999999999999)

@csrf_exempt   # disables csrf protection for this view
def new(request):
    if request.method == 'POST':
        mail = request.POST['email']
        if "@" in mail:         # error warning for @ missing
            sub = Subscriber(email=request.POST['email'], conf_num=random_digits())
            if Subscriber.objects.filter(email = mail).exists():   # catching integrity error from duplicate email added
                return render(request, 'newsletter.html', {'email': sub.email, 'action': 'registered previously', 'form': SubscriberForm()})
            else:
                sub.save()
                message = Mail(
                    from_email=settings.FROM_EMAIL,
                    to_emails=sub.email,
                    subject='Newsletter Confirmation',
                    html_content='Thank you for signing up for our Astronomy Shop email newsletter! \
                        Please complete the process by \
                        <a href="{}?email={}&conf_num={}"> clicking here to \
                        confirm your registration</a>.'.format(request.build_absolute_uri('/confirm/'),
                                                    sub.email,
                                                    sub.conf_num))
                sg = SendGridAPIClient(settings.SENDGRID_API_KEY)   # uses sendgrid system
                response = sg.send(message)
                return render(request, 'newsletter.html', {'email': sub.email, 'action': 'added', 'form': SubscriberForm()})
        else:
            return render(request, 'newsletter.html', {'email': mail, 'action': 'is not a valid address, please try again', 'form': SubscriberForm()})
    else:
            return render(request, 'newsletter.html', {'form': SubscriberForm()})

# user confirm subscription
def confirm(request):
    sub = Subscriber.objects.get(email=request.GET['email'])
    if sub.conf_num == request.GET['conf_num']:
        sub.confirmed = True
        sub.save()
        return render(request, 'newsletter.html', {'email': sub.email, 'action': 'confirmed'})
    else:
        return render(request, 'newsletter.html', {'email': sub.email, 'action': 'denied'})

# user deletes subscription
def delete(request):
    sub = Subscriber.objects.get(email=request.GET['email'])
    if sub.conf_num == request.GET['conf_num']:
        sub.delete()
        return render(request, 'newsletter.html', {'email': sub.email, 'action': 'unsubscribed'})
    else:
        return render(request, 'newsletter.html', {'email': sub.email, 'action': 'denied'})

# used for terms and conditions page
def terms(request):
    return render(request, 'terms.html')

voucher/views.py
from django.shortcuts import redirect
from django.utils import timezone
from django.views.decorators.http import require_POST
from .models import Voucher
from .forms import VoucherApplyForm

def voucher_apply(request):
    now = timezone.now()
    form = VoucherApplyForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']
        try:
            voucher = Voucher.objects.get(code__iexact = code, valid_from__lte = now, valid_to__gte =now, active=True)
            request.session['voucher_id'] = voucher.id
        except Voucher.DoesNotExist:
            request.session['voucher_id'] = None
    return redirect('cart:cart_detail')

management/templates/categories.html
{% extends "shop_base.html" %}
{% block content %}
<div class="container h-100 mt-5">
    <a class="btn btn-link fas fa-long-arrow-alt-left" style="vertical-align:middle" href="{% url 'management:management' %}">Back to Console</a>
    <a class="btn btn-link fas fa-plus" style="vertical-align:middle" href="{% url 'management:cat_add' %}">Add category</a></p>
    List of our categories:
    {% for cat in category_list %}
    <div>       
        <a href="{% url 'management:cat_details' cat.slug %}">Name: {{ cat.name }} ID:{{ cat.slug }} </a> 
    </div>
    {% endfor%}

    
</div>

{% endblock content %}

management/templates/category_delete.html
{% extends "shop_base.html" %}
{% block title %}Delete Category{% endblock title %}
{% block content %}
<div class="container h-100 mt-5">
</br>
  <h1>Delete</h1>
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ category.name }}"?</p>
    <button class="btn btn-danger ml-2 fas fa-trash" type="submit">Confirm</button>
  </form>
</br>
</div>
{% endblock content %}

management/templates/category_details.html
{% extends "shop_base.html" %}
{% block content %}
<div class="container h-100 mt-5">
    <p> Category details:</p>
    
    <div>
        <p>Name:  {{ category.name }} </p>

    </div>
    <p> Actions:
        <a class="btn btn-link fas fa-long-arrow-alt-left" style="vertical-align:middle" href="/management/shop_management/categories/">Back</a>
        <a href="{% url 'management:cat_update' category.slug %}" class="btn btn-link fas fa-edit" >Edit category</a> 
        <a href="{% url 'management:cat_delete' category.slug %}" class="btn btn-link fas fa-trash" >Delete category</a> 
    </p>
</div>

{% endblock content %}

management/templates/picture_delete.html
{% extends "shop_base.html" %}
{% block title %}Delete Ppicture{% endblock title %}
{% block content %}
<div class="container h-100 mt-5">
</br>
  <h1>Delete picture</h1>
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ picture.title }}"?</p>
    <button class="btn btn-danger ml-2 fas fa-trash" type="submit">Confirm</button>
  </form>
</br>
</div>
{% endblock content %}

management/templates/picture_edit.html
{% extends "shop_base.html" %}
{% block title %}Edit Picture{% endblock title %}
{% block content %}
<div class="container h-100 mt-5">
</br>
  <h1>Edit picture</h1>
  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-info ml-2 fas fa-edit" type="submit">Update</button>
  </form>
</br>
</div>
{% endblock content %}

management/templates/profile_edit.html
{% extends "shop_base.html" %}
{% block title %}Edit Profile{% endblock title %}
{% block content %}
<div class="container h-100 mt-5">
</br>
  <h1>Edit profile</h1>
  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-info ml-2 fas fa-edit" type="submit">Update</button>
  </form>
</br>
</div>
{% endblock content %}

management/templates/shop_management.html
{% extends "shop_base.html" %}
{% block content %}
<div class="container h-100 mt-5">
    <a class="btn btn-link" style="vertical-align:middle" href="{% url 'management:cats' %}">Categories</a></p>
    <a class="btn btn-link" style="vertical-align:middle" href="{% url 'management:products' %}">Products</a></p>
    <a class="btn btn-link" style="vertical-align:middle" href="{% url 'management:sliders' %}">Sliders</a></p>
</div>

{% endblock content %}

management/templates/subscriber_add.html
{% extends "shop_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add subscriber{% endblock title %}
{% block content %}
<div class="container h-100 mt-5">
  <h1>New subscriber</h1>
  <form method = "post" enctype="multipart/form-data"> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <button class="btn btn-info ml-2 fas fa-upload" type="submit">Upload</button> 
</form> 
</br>
</div>

{% endblock content %}

management/templates/subscriber_details.html
{% extends "shop_base.html" %}
{% block content %}
<div class="container h-100 mt-5">
    <p> Subscriber details:</p>
    
    <div>
        <p>Email:  {{ subscriber.email }} </p>
        <p>Confirmed:  {{ subscriber.confirmed }} </p>

    </div>
    <p> Actions:
        <a class="btn btn-link fas fa-long-arrow-alt-left" style="vertical-align:middle" href="{% url 'management:subscribers' %}">Back</a>
        <a href="{% url 'management:subscriber_update' subscriber.id %}" class="btn btn-link fas fa-edit" >Edit subscriber</a>
        <a href="{% url 'management:subscriber_delete' subscriber.id %}" class="btn btn-link fas fa-trash" >Delete subscriber</a>
    </p>
</div>

{% endblock content %}

management/templates/subscriber_edit.html
{% extends "shop_base.html" %}
{% block title %}Edit Subscriber{% endblock title %}
{% block content %}
<div class="container h-100 mt-5">
</br>
  <h1>Edit</h1>
  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-info ml-2 fas fa-edit" type="submit">Update</button>
  </form>
</br>
</div>
{% endblock content %}

management/templates/subscribers.html
{% extends "shop_base.html" %}
{% block content %}
<div class="container h-100 mt-5">
    <a class="btn btn-link fas fa-long-arrow-alt-left" style="vertical-align:middle" href="{% url 'management:management' %}">Back to Console</a>
    <a class="btn btn-link fas fa-plus" style="vertical-align:middle" href="{% url 'management:subscriber_add' %}">Add subscriber</a></p>
    List of our subscribers:
    {% for sub in subscriber_list %}
    <div>       
        <a href="{% url 'management:subscriber_details' sub.pk %}"> Subscriber email:  {{ sub.email }} </a> 
    </div>
    {% endfor%}

    
</div>

{% endblock content %}

management/templates/user_edit.html
{% extends "shop_base.html" %}
{% block title %}Edit User{% endblock title %}
{% block content %}
<div class="container h-100 mt-5">
</br>
  <h1>Edit</h1>
  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-info ml-2 fas fa-long-arrow-alt-left" type="submit" href="{% url 'management:users' %}">Back</button>
    <button class="btn btn-info ml-2 fas fa-edit" type="submit">Update</button>
  </form>
</br>
</div>
{% endblock content %}

<a class="btn btn-link fas fa-long-arrow-alt-left" style="vertical-align:middle" href="{% url 'management:users' %}">Back</a>

management/templates/voucher_delete.html
{% extends "shop_base.html" %}
{% block title %}Delete Voucher{% endblock title %}
{% block content %}
<div class="container h-100 mt-5">
</br>
  <h1>Delete</h1>
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete voucher "{{ voucher.code }}"?</p>
    <button class="btn btn-danger ml-2 fas fa-trash" type="submit">Confirm</button>
  </form>
</br>
</div>
{% endblock content %}

management/templates/voucher_details.html
{% extends "shop_base.html" %}
{% block content %}
<div class="container h-100 mt-5">
    <p> Voucher details:</p>    
    <div>
        <p>Code:  {{ voucher.code }} </p>
        <p>Valid from:  {{ voucher.valid_from }} </p>
        <p>Valid to:  {{ voucher.valid_to }} </p>
        <p>Discount:  {{ voucher.discount }} </p>
        <p>Is active:  {{ voucher.active }} </p>
    </div>
    <p> Actions:
        <a class="btn btn-link fas fa-long-arrow-alt-left" style="vertical-align:middle" href="{% url 'management:vouchers' %}">Back</a>
        <a href="{% url 'management:voucher_update' voucher.id %}" class="btn btn-link fas fa-edit" >Edit voucher</a>
        <a href="{% url 'management:voucher_delete' voucher.id %}" class="btn btn-link fas fa-trash" >Delete voucher</a>
    </p>
</div>

{% endblock content %}