astro_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as user_views
from django.views.generic.base import TemplateView
from newsletter import views
from accounts import views as user_views



urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include ('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),    
    path('', include('pages.urls')),
    path('store/', include('store.urls')),
    path('profile/', user_views.profile, name='profile'),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('voucher/', include('voucher.urls', namespace='voucher')),
    path('contact', include('contact_us.urls')),
    path('new/', views.new, name='new'),
    path('confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
    path('gallery/', include('gallery.urls')),
    path('management/', include('management.urls')),
    path('search/', include('search_app.urls')),
    path('terms/', views.terms, name='terms'),
    #path('newsletter/', include('newsletter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

management/urls.py
from django.urls import path
from .views import UserManagementView, UserListView, UserDetailView, UserDeleteView, UserUpdateView #, UserCreateView
from .views import ShopManagementView, CategoryListView, CategoryCreateView, CategoryDeleteView, CategoryUpdateView, CategoryDetailView
from .views import ProductListView, ProductCreateView, ProductDeleteView, ProductDetailView, ProductUpdateView
from .views import VoucherListView, VoucherCreateView, VoucherDeleteView, VoucherDetailView, VoucherUpdateView
from .views import ProfileListView, ProfileCreateView, ProfileDeleteView, ProfileDetailView, ProfileUpdateView
from .views import SubscriberListView, SubscriberCreateView, SubscriberDeleteView, SubscriberDetailView, SubscriberUpdateView
from .views import NewsletterListView, NewsletterCreateView, NewsletterDeleteView, NewsletterDetailView, NewsletterUpdateView
from .views import PictureListView, PictureCreateView, PictureDeleteView, PictureDetailView, PictureUpdateView
from .views import PictureOfTheMonthListView, PictureOfTheMonthDeleteView
from .views import SliderListView, SliderCreateView, SliderDeleteView
from accounts.views import signupView



app_name='management'


urlpatterns = [
    path('', UserManagementView.as_view(), name = 'management'),
    path('user_management/', UserListView.as_view(), name = 'users'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name = 'user_details'),
    path('user_add/', signupView, name = 'user_add'),
    path('user_delete/<int:pk>/', UserDeleteView.as_view(), name = 'user_delete'),
    path('user_update/<int:pk>/', UserUpdateView.as_view(), name = 'user_update'),

    path('profiles/', ProfileListView.as_view(), name = 'profiles'),
    path('profile_detail/<int:pk>/', ProfileDetailView.as_view(), name = 'profile_details'),
    path('profile_add/', ProfileCreateView.as_view(), name = 'profile_add'),
    path('profile_delete/<int:pk>/', ProfileDeleteView.as_view(), name = 'profile_delete'),
    path('profile_update/<int:pk>/', ProfileUpdateView.as_view(), name = 'profile_update'),

    path('subscribers/', SubscriberListView.as_view(), name = 'subscribers'),
    path('subscriber_detail/<int:pk>/', SubscriberDetailView.as_view(), name = 'subscriber_details'),
    path('subscriber_add/', SubscriberCreateView.as_view(), name = 'subscriber_add'),
    path('subscriber_delete/<int:pk>/', SubscriberDeleteView.as_view(), name = 'subscriber_delete'),
    path('subscriber_update/<int:pk>/', SubscriberUpdateView.as_view(), name = 'subscriber_update'),

    path('newsletters/', NewsletterListView.as_view(), name = 'newsletters'),
    path('newsletter_detail/<int:pk>/', NewsletterDetailView.as_view(), name = 'newsletter_details'),
    path('newsletter_add/', NewsletterCreateView.as_view(), name = 'newsletter_add'),
    path('newsletter_delete/<int:pk>/', NewsletterDeleteView.as_view(), name = 'newsletter_delete'),
    path('newsletter_update/<int:pk>/', NewsletterUpdateView.as_view(), name = 'newsletter_update'),

    path('shop_management/', ShopManagementView.as_view(), name = 'manage_shop'),
    path('shop_management/categories/', CategoryListView.as_view(), name = 'cats'),
    path('shop_management/categories/<slug:slug>/', CategoryDetailView.as_view(), name = 'cat_details'),
    path('shop_management/categories/category_add', CategoryCreateView.as_view(), name = 'cat_add'),
    path('shop_management/categories/category_delete/<slug:slug>/', CategoryDeleteView.as_view(), name = 'cat_delete'),
    path('shop_management/categories/category_update/<slug:slug>/', CategoryUpdateView.as_view(), name = 'cat_update'),

    path('shop_management/products/', ProductListView.as_view(), name = 'products'),
    path('shop_management/products/<slug:slug>/', ProductDetailView.as_view(), name = 'prod_details'),
    path('shop_management/products/product_add', ProductCreateView.as_view(), name = 'prod_add'),
    path('shop_management/products/product_delete/<slug:slug>/', ProductDeleteView.as_view(), name = 'prod_delete'),
    path('shop_management/products/product_update/<slug:slug>/', ProductUpdateView.as_view(), name = 'prod_update'),

    path('shop_management/sliders/', SliderListView.as_view(), name = 'sliders'),
    path('shop_management/products/slider_add', SliderCreateView.as_view(), name = 'slider_add'),
    path('shop_management/products/slider_delete/<int:pk>/', SliderDeleteView.as_view(), name = 'slider_delete'),

    path('shop_management/vouchers/', VoucherListView.as_view(), name = 'vouchers'),
    path('shop_management/vouchers/<int:pk>/', VoucherDetailView.as_view(), name = 'voucher_details'),
    path('shop_management/vouchers/product_add', VoucherCreateView.as_view(), name = 'voucher_add'),
    path('shop_management/vouchers/product_delete/<int:pk>/', VoucherDeleteView.as_view(), name = 'voucher_delete'),
    path('shop_management/vouchers/product_update/<int:pk>/', VoucherUpdateView.as_view(), name = 'voucher_update'),

    path('shop_management/pictures/', PictureListView.as_view(), name = 'pictures'),
    path('shop_management/pictures/<uuid:pk>/', PictureDetailView.as_view(), name = 'picture_details'),
    path('shop_management/pictures/picture_add', PictureCreateView.as_view(), name = 'picture_add'),
    path('shop_management/pictures/picture_delete/<uuid:pk>/', PictureDeleteView.as_view(), name = 'picture_delete'),
    path('shop_management/pictures/picture_update/<uuid:pk>/', PictureUpdateView.as_view(), name = 'picture_update'),

    path('shop_management/pictures_of_the_month/', PictureOfTheMonthListView.as_view(), name = 'pictures_of_the_month'),
    path('shop_management/pictures_of_the_month/picture_of_the_month_delete/<int:pk>/', PictureOfTheMonthDeleteView.as_view(), name = 'picture_of_the_month_delete'),

]

order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name = 'thanks'),
    path('history/', views.orderHistory, name = 'order_history'),
    path('<int:order_id>/', views.viewOrder, name = 'order_detail'),
]

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
    path('', views.searchResult, name='searchResult')
]

store/urls.py
from django.urls import path
from . import views

app_name='store'


urlpatterns = [
    path('<slug:category_slug>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
]

newsletter/models.py
from django.db import models
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Email, Content, Mail
from django.conf import settings

class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    conf_num = models.CharField(max_length=15)
    confirmed = models.BooleanField(default=False)

    # confirm (or not) the subscription (also casts to lower to stop duplication in DB due to different letter cases duplicating)
    def __str__(self):
        return self.email.lower() + " (" + ("not " if not self.confirmed else "") + "confirmed)"

# model for the newsletter (using sendgrid)
class Newsletter(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    subject = models.CharField(max_length=150)
    contents = models.FileField(upload_to='uploaded_newsletters/')

    def __str__(self):
        return self.subject + " " + self.created_at.strftime("%B %d, %Y")

    def send(self, request):
        contents = self.contents.read().decode('utf-8')
        subscribers = Subscriber.objects.filter(confirmed=True)
        sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
        for sub in subscribers:
            message = Mail(
                    from_email=settings.FROM_EMAIL,
                    to_emails=sub.email,
                    subject=self.subject,
                    html_content=contents + (
                        '<br><a href="{}/delete/?email={}&conf_num={}">Unsubscribe</a>.').format(
                            request.build_absolute_uri('/delete/'),
                            sub.email,
                            sub.conf_num))
            sg.send(message)

newsletter/forms.py
from django import forms

class SubscriberForm(forms.Form):
    email = forms.EmailField(label='Please enter your email below to learn about our latest offers, products and news',
                             max_length=100,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

newsletter/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from .models import Subscriber
from .forms import SubscriberForm
import random
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# random num for confirmation number
def random_digits():
    return "%0.12d" % random.randint(0, 999999999999)

@csrf_exempt   # disables csrf protection for this view
def new(request):
    if request.method == 'POST':
        mail = request.POST['email']
        if "@" in mail:         # error warning for @ missing
            sub = Subscriber(email=request.POST['email'], conf_num=random_digits())
            if Subscriber.objects.filter(email = mail).exists():   # catching integrity error from duplicate email added
                return render(request, 'newsletter.html', {'email': sub.email, 'action': 'registered previously', 'form': SubscriberForm()})
            else:
                sub.save()
                message = Mail(
                    from_email=settings.FROM_EMAIL,
                    to_emails=sub.email,
                    subject='Newsletter Confirmation',
                    html_content='Thank you for signing up for our Astronomy Shop email newsletter! \
                        Please complete the process by \
                        <a href="{}?email={}&conf_num={}"> clicking here to \
                        confirm your registration</a>.'.format(request.build_absolute_uri('/confirm/'),
                                                    sub.email,
                                                    sub.conf_num))
                sg = SendGridAPIClient(settings.SENDGRID_API_KEY)   # uses sendgrid system
                response = sg.send(message)
                return render(request, 'newsletter.html', {'email': sub.email, 'action': 'added', 'form': SubscriberForm()})
        else:
            return render(request, 'newsletter.html', {'email': mail, 'action': 'is not a valid address, please try again', 'form': SubscriberForm()})
    else:
            return render(request, 'newsletter.html', {'form': SubscriberForm()})

# user confirm subscription
def confirm(request):
    sub = Subscriber.objects.get(email=request.GET['email'])
    if sub.conf_num == request.GET['conf_num']:
        sub.confirmed = True
        sub.save()
        return render(request, 'newsletter.html', {'email': sub.email, 'action': 'confirmed'})
    else:
        return render(request, 'newsletter.html', {'email': sub.email, 'action': 'denied'})

# user deletes subscription
def delete(request):
    sub = Subscriber.objects.get(email=request.GET['email'])
    if sub.conf_num == request.GET['conf_num']:
        sub.delete()
        return render(request, 'newsletter.html', {'email': sub.email, 'action': 'unsubscribed'})
    else:
        return render(request, 'newsletter.html', {'email': sub.email, 'action': 'denied'})

# used for terms and conditions page
def terms(request):
    return render(request, 'terms.html')

templates/base.html
<!-- {% load cookielaw_tags %} -->
{% load static %}
<html>
    <head>
      <title>{% block title %}AstroView Home{% endblock title %}</title>
        <meta charset="UTF-8">
        
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script> 
        <link rel="shortcut icon" href="{% static 'images/icon.png' type='image/x-icon' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        
    </head>
    <body class="home-image">
      {% load i18n static%}
      <!-- <script src="{% static 'js/cookielaw.js' %}"></script>
      <div id="CookielawBanner">
          <div class="cookies text-white">
              <h6>{% trans "COOKIE_INFO_HEADER" %}</h6>
              <p>
                  <a class="btn-red btn-primary pull-right" href="javascript:Cookielaw.createCookielawCookie();">{% trans "COOKIE_INFO_OK" %}</a>
                  {% trans "COOKIE_INFO_PARA" %}
              </p>
          </div>
      </div> -->

        <header>
          {% include 'login_navbar.html' %}    
        </header>
        <!-- {% cookielaw_banner %} -->
        <div>
            <!-- {% include 'messages.html' %} -->
            {% block content %}
            {% endblock content %}
        </div>
      
      
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      
<!-- alert message -->
      <script>
        setTimeout(function(){
          if ($('#msg').length > 0) {
            $('#msg').remove();
          }
        }, 2000)
      </script>
<!-- alert message  end-->

<!-- Cookies law popup start-->


<!-- <script type="application/javascript">
    $(document).ready(function () {
       $('.close-cookies').click(function () {
           $(this).parent().hide();
       });
    });
</script> -->
<!-- Cookies law popup end--> 
  </body>
  <div class = "footer text-center">
    <p> ©Copyright 2021 <br>
    <br>
    <a href="https://www.facebook.com/Astronomy-Shop-112951760891797"><img  src="/static/images/facebook.png"  alt="facebook" style="width: 2%;"/></a>
    <a href="https://twitter.com/sam20619241"><img  src="/static/images/twitter1.png" href="https://www.facebook.com/" style="width: 2%"/></a>
    <a href="https://www.instgram.com/astronomyproject28/"><img  src="/static/images/instagram1.png" href="https://www.facebook.com/" style="width: 2%"/></a>
    <a style="float: left; margin-left: 2em;" href="{% url 'new' %}">Sign Up To Our Mailing List</a>
    <a style="float: right; margin-right: 2em;" href="{% url 'terms' %}">Terms & Conditions</a>
    </p>
    <br>
  </div>
</html>

templates/category_detail.html
{% extends "shop_base.html" %}
{% load static %}
{% block title %}{{ category.name }}{% endblock %}
{% block content %}

<div class ="container pt-5">
	<div class="row">
		<div class = "mx-auto">
		<p><a href="{% url 'shop' %}">Back to Shop</a> 
	</div>	
	</div>
	<div class = "row">
		<div class="col-4 category_image">
			{% if category.image_secondary %}
			<img src = "{{category.image_secondary.url}}" alt = "{{ category.title }}">		
			{% endif %}	
		</div>
		<div class="col-6">
			<div>
				<h1 >Products in {{category.name}}</h1>
				<p></p>
			</div>
		</div>
	</div>
	<!-- 
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>
	-->
    <br>

		<div class="row">
			{% for product in products.object_list %}
			<div class="col-lg-4 col-md-6 col-12 my-3">
				<div class = "card text-center h-100 ">
					<a href="{% url 'store:product_detail' category.slug product.slug %}"><img class ="card-img-top" src="{{product.image.url}}" alt="{{product.name}}"></a>
					<div class="card-footer mt-auto">
						<h4>{{product.name}}</h4>
					</div>
				</div>
			</div>
			{% endfor %} 
		</div>	
		<div class="mx-auto">
			{% if products.paginator.num_pages > 1 %}
				<hr>
				<div class="text-center">
					{% for pg in products.paginator.page_range %}
					<a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}
					</a>
					{% endfor %}
				</div>
			{% endif %}
		</div>
		<br>	
</div>
{% endblock %}

templates/login_navbar.html
{% load static %}
<nav class="navbar navbar-expand justify-content-center mt-4 mb-5">
  <div class = "container-fluid">
    <ul class="nav navbar-nav bounce">
      <!-- <a href="javascript:void(0);" class="icon" onclick="myFunction()"><i class="fa fa-bars"></i></a> -->
      <li class="nav-item"><a class="hoverable nav-link fas fa-home" href="{% url 'home' %}"> Home</a></li>
      <li class="nav-item"><a class="hoverable nav-link fab fa-shopify" style="font-weight: bold;" href="{% url 'shop' %}"> Shop</a></li>
      <li class="nav-item"><a class="hoverable nav-link fas fa-image" href="{% url 'gallery' %}"> Gallery</a></li>
      <li class="nav-item"><a class="hoverable nav-link fas fa-phone" href="{% url 'contact' %}"> Contact</a></li>
    </ul>

    <ul class="drop_nav navbar-nav bounce navbar-right ">
      {% if user.is_authenticated %}
          <li class="nav-item dropdown hoverable">
            <a href="#" class="nav-link dropdown-toggle fas fa-door-open" data-toggle="dropdown" 
            >Welcome, {{ user.username }}</a> 
          <div class="dropdown-menu">
            <a class="hoverable nav-link" href ="{% url 'profile' %}" class = "dropdown-item">Profile {% if user.profile.image %}
              <img class="rounded-circle account-img " src="{{ user.profile.image.url }}" style="width: 10%">
            {% endif %}</a>
            <a class="hoverable nav-link" href = "{% url 'order:order_history' %}" class = "dropdown-item">Order History <i class="fas fa-list-alt"></i></a>              
            {% if user.is_staff %}
            <a class="hoverable nav-link" href="{% url 'management:management' %}">Console <i class="fas fa-user-cog"></i></a>  
            {% endif %}      
            <a class="hoverable nav-link" href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>          
          </div>
        </li>
        {% else %}
        <li>
          <a class="hoverable nav-link" href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
        </li>
        {% endif %}
        <li class="nav-item"><a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>{{item_count}}</a></li>
      </ul>
  </div>
  </nav>   
  <script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "nav") {
        x.className += " responsive";
      } else {
        x.className = "nav";
      }
    }

    </script> 

templates/login_navbar_shop.html
{% load static %}
<nav class="navbar navbar-expand justify-content-center mt-4 mb-5">
  <div class = "container-fluid">
    <ul class="nav navbar-nav bounce">
      <li class="nav-item"><a class="hoverable nav-link text-dark fas fa-home" href="{% url 'home' %}"> Home</a></li>
      <li class="nav-item"><a class="hoverable nav-link text-dark fab fa-shopify" style="font-weight: bold;" href="{% url 'shop' %}"> Shop</a></li>
      <li class="nav-item"><a class="hoverable nav-link text-dark fas fa-image" href="{% url 'gallery' %}"> Gallery</a></li>
      <li class="nav-item"><a class="hoverable nav-link text-dark fas fa-phone" href="{% url 'contact' %}"> Contact</a></li>
    </ul>

    <ul class="drop_nav navbar-nav bounce navbar-right ">
      {% if user.is_authenticated %}
          <li class="nav-item dropdown hoverable">
            <a href="#" class="nav-link dropdown-toggle text-dark fas fa-door-open" data-toggle="dropdown" 
            >Welcome, {{ user.username }}</a> 
          <div class="dropdown-menu">
            <a class="hoverable nav-link  text-dark" href ="{% url 'profile' %}" class = "dropdown-item">Profile {% if user.profile.image %}
              <img class="rounded-circle account-img " src="{{ user.profile.image.url }}" style="width: 10%">
            {% endif %}</a>
            <a class="hoverable nav-link text-dark" href = "{% url 'order:order_history' %}" class = "dropdown-item">Order History <i class="fas fa-list-alt"></i></a>              
            {% if user.is_staff %}
            <a class="hoverable nav-link text-dark" href="{% url 'management:management' %}">Console <i class="fas fa-user-cog"></i></a>  
            {% endif %}      
            <a class="hoverable nav-link text-dark" href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>          
          </div>
        </li>
        {% else %}
        <li>
          <a class="hoverable nav-link text-dark" href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
        </li>
        {% endif %}
        <li class="nav-item"><a class="nav-link text-dark" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>{{item_count}}</a></li>
      </ul>
  </div>
  </nav>   
  <script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "nav") {
        x.className += " responsive";
      } else {
        x.className = "nav";
      }
    }

    </script> 

templates/product.html
{% extends "shop_base.html" %}
{% load static %}
{% block metadescription %}
{{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}{{ product.name }} {% endblock %}
{% block content %}
<div class="container pt-5 h-100">
	<div class="row my_row_class">
		<div class = "mx-auto">
		<!-- breadcrumb for navigation page, javascript (-1) for 'back' button-->	
		<p><a href="{% url 'shop' %}">Shop Home</a> | <a href="javascript:history.go(-1)">Go Back</a> | {{product.name}}</p>
	</div>	
	</div>
	<div>
		<br>
		<div class = "row">			
			<div class = "col-5 prod_image">				
				<img src="{{product.image.url}}" alt="{{product.name}}" style="max-height: 350px;">				
			</div>
			<div class = col-7>
				<div class = "row">
					<div class = col-6>
						<h1>{{product.name}}</h1>
						<br>
						<p>Make: {{product.make}}</p>
						<p>Model: {{product.model}}</p>
						<p>Price: €{{product.price}}</p>
						<br><br><br>
						{% if product.stock == 0%}
						<p><b>Out of Stock</b></p>
						{% else %}
						<a class="btn btn-primary fas fa-cart-plus" href="{% url 'cart:add_cart' product.id %}">  Add to Cart</a>
						{% endif %}
					</div>
					<div class = "col-3">
						<h1>Product Description</h1>
						<p>{{product.description}}</p>						
					</div>
				</div>
			</div>			
		</div>
	</div>
</div>
{% endblock %}

templates/shop.html
{% extends "shop_base.html" %}
{% load static %}
{% block title %}AstroView Shop{% endblock title %}
{% block content %}

<div class ="container mt-5">
	<div>
		<h1>Our Products Collection</h1>

		<div id="carouselExampleIndicators" class="carousel slide py-2 mt-2 mb-5 zindex-tooltip" data-ride="carousel">
			<!-- <ol class="carousel-indicators">
				{% for obj in slides %}
					{% if forloop.first %}
						<li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}" class="active"></li>
					{% else %}
						<li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}"></li>		
					{% endif %}
				{% endfor %}
			  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			</ol> -->
			<div class="carousel-inner bg-light">
				{% for obj in slides %}
					{% if forloop.first %}
					<div class="carousel-item active">
					{% else %}
					<div class="carousel-item">
					{% endif %}	<p class = "text-center pt-1">{{obj.slide.name}}</p>
					<a href="{% url 'store:product_detail' obj.slide.category.slug obj.slide.slug %}">
						<img class="d-block w-50 h-50 mx-auto pb-2" class="h-50 d-inline-block" src="{{ obj.slide.image.url }}" alt="{{obj.slide.name}}"></a>													
					</div>							
				{% endfor %}
				</div>
			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			  <span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			  <span class="carousel-control-next-icon" aria-hidden="true"></span>
			  <span class="sr-only">Next</span>
			</a>
			</div>
		</div>


		<div class="row mt-3">
			<div class = "mr-3">
				<form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult'%}" method="get">
					{% csrf_token %}
					<input class="form-control mr-sm-2" type="search" placeholder="Search Category &#8981" aria-label="Search" name="cat">
					<button class="btn bg-primary my-2 my-sm-0" type="submit">Search &#8981</button>
				</form>
			</div>
			<div>
				<form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult'%}" method="get">
					{% csrf_token %}
					<input class="form-control mr-sm-2" type="search" placeholder="Search Product &#8981" aria-label="Search" name="prod">
					<button class="btn bg-primary my-2 my-sm-0" type="submit">Search &#8981</button>
				</form>
			</div>
		</div>


	<!--Dark Mode-->
	<!-- <button onclick="myFunction()" class="fa fa-adjust">Toggle dark mode</button> -->
	<div class="row">
		<div class="row h-100">
			{% for category in menu_categories %}
			<div class="col-lg-4 col-md-6 col-12 my-3">
				<div class = "card text-center h-100">
					<a href="{% url 'store:category_detail' category.slug %}"><img class ="card-img-top" src="{{category.image.url}}" alt="{{category.name}}"></a>
					<div class="card-footer mt-auto">
						<h4>{{category.name}}</h4>
					</div>
				</div>
			</div>
			{% endfor %} 
		</div>
	</div>
</div>
<script>
	function myFunction() {
	   var element = document.body;
	   element.classList.toggle("dark-mode");
	}
	</script>

{% endblock %}